In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
a.shape

(5, 3)

In [5]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(c[1,1])
#If I want the first (python-first, so 0-indexed) row?
print(c[1,:]) 
#First column
print(c[:,1])
#What if I want the end of the first row? Say, from the middle to the end?
print(c[1,1:]) #This is fun! We fix the row number and we use a slice for the columns. 

5
[4 5 6]
[2 5]
[5 6]


In [20]:
#Back to a larger structure
a = np.zeros((5,3))
print(a)
a[1,1] = 777 #One particular element
a[-2:, -2:] = 1 #Bottom right corner

print('make the spiderman cast shadow')
a[2, :] = a[1,:]/7 # Make the human-third (python-2ns)
print(a)

# Make 0-th column the sum of the other two
#Manually
a[:,0] = a[:,1] + a[:,2]
print('the new truth')

#Another: smarter way
a[:,0] = np.sum(a[:,1:], axis=1) #in this case, don't forget to tell that you want horizontal squishing
print('yet another attempt,', a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
make the spiderman cast shadow
[[  0.   0.   0.]
 [  0. 777.   0.]
 [  0. 111.   0.]
 [  0.   1.   1.]
 [  0.   1.   1.]]
the new truth
yet another attempt, [[  0.   0.   0.]
 [777. 777.   0.]
 [111. 111.   0.]
 [  2.   1.   1.]
 [  2.   1.   1.]]
